name: Exercise 8

on: 
  workflow_dispatch: 

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: generate a random num and store it in a env var 
        run:  echo "NUM=$RANDOM" >> $GITHUB_ENV
        
      - name: print the random number 
        run: echo "the random num is ${{env.NUM}}"
